[package]
name = "prio"
version = "0.4.0"
authors = ["Josh Aas <jaas@kflag.net>", "Karl Tarbe <tarbe@apple.com>"]
edition = "2018"
description = "Implementation of the Prio aggregation system core: https://crypto.stanford.edu/prio/"
license = "MPL-2.0"
repository = "https://github.com/abetterinternet/libprio-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes-ctr = "0.4.0"
aes-gcm = "0.6.0"
base64 = "0.12.3"
hpke = "0.5.1"
rand = "0.8.3"
ring = "0.16.15"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
assert_matches = "1.5.0"
criterion = "0.3"
modinverse = "0.1.0"
num-bigint = "0.4.0"
serde_json = "1.0"

[[bench]]
name = "speed_tests"
harness = false

[[example]]
name = "sum"
